---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
      - feat/*
  schedule:
    - cron: "0 7 * * 0"

defaults:
  run:
    working-directory: 'geerlingguy.docker'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'geerlingguy.docker'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .
          
  scan-dependencies:
    name: Scan dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Perform integration testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.11
          pre-test-cmd: echo This runs before the ansible-test invocation
          python-version: 3.9
          target-python-version: 3.9
          testing-type: integration
          test-deps: ansible.netcommon
      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.11
          testing-type: sanity
      - name: Perform unit testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.11
          pre-test-cmd: echo This runs before the ansible-test invocation
          python-version: 3.9
          target-python-version: 3.9
          testing-type: units
          test-deps: >-
            ansible.netcommon
            ansible.utils

    
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - rockylinux8
          - centos7
          - ubuntu2004
          - ubuntu1804
          - debian11
          - debian10
          - debian9
          - fedora34

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'geerlingguy.docker'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
